#include "overrides.h"

static const struct core_override_option gambatte_core_option_overrides[] = {
	{
		.key = "gambatte_gb_colorization",
		.info = "'Auto' selects the 'best' palette. 'Internal' uses 'Internal Palette' option. 'Custom' loads user palette from system directory.",
	},
	{
		.key = "gambatte_gb_internal_palette",
		.info = "Selects palette used when 'GB Colorization' is set to 'Internal.'",
		.options = {
			[50] = { "Special 4", NULL },
		}
	},
	{
		.key = "gambatte_gb_palette_twb64_1",
		.desc = "TWB64 - Pack 1",
		.default_value = "Aqours Blue",
		.options = {
			{ "Aqours Blue",               NULL },
			{ "Anime Expo Ver.",           NULL },
			{ "SpongeBob Yellow",          NULL },
			{ "Patrick Star Pink",         NULL },
			{ "Neon Red",                  NULL },
			{ "Neon Blue",                 NULL },
			{ "Neon Yellow",               NULL },
			{ "Neon Green",                NULL },
			{ "Neon Pink",                 NULL },
			{ "Mario Red",                 NULL },
			{ "Nick Orange",               NULL },
			{ "Virtual Boy Ver.",          NULL },
			{ "Golden Wild",               NULL },
			{ "Builder Yellow",            NULL },
			{ "Classic Blurple",           NULL },
			{ "765 Production Ver.",       NULL },
			{ "Superball Ivory",           NULL },
			{ "Crunchyroll Orange",        NULL },
			{ "Muse Pink",                 NULL },
			{ "Nijigasaki Yellow",         NULL },
			{ "Gamate Ver.",               NULL },
			{ "Greenscale Ver.",           NULL },
			{ "Odyssey Gold",              NULL },
			{ "Super Saiyan God",          NULL },
			{ "Super Saiyan Blue",         NULL },
			{ "Bizarre Pink",              NULL },
			{ "Switch Lite Ver.",          NULL },
			{ "Game.com Ver.",             NULL },
			{ "Sanrio Pink",               NULL },
			{ "BANDAI NAMCO Ver.",         NULL },
			{ "Cosmo Green",               NULL },
			{ "Wanda Pink",                NULL },
			{ "Zelda DX Ver.",             NULL },
			{ "Travel Wood",               NULL },
			{ "Pokemon Ver.",              NULL },
			{ "Game Grump Orange",         NULL },
			{ "Scooby-Doo Ver.",           NULL },
			{ "Pokemon mini Ver.",         NULL },
			{ "Supervision Ver.",          NULL },
			{ "DMG Ver.",                  NULL },
			{ "Pocket Ver.",               NULL },
			{ "Light Ver.",                NULL },
			{ "Miraitowa Blue",            NULL },
			{ "Someity Pink",              NULL },
			{ "Pikachu Yellow",            NULL },
			{ "Eevee Brown",               NULL },
			{ "Microvision Ver.",          NULL },
			{ "TI-83 Ver.",                NULL },
			{ "Aegis Cherry",              NULL },
			{ "Labo Fawn",                 NULL },
			{ "MILLION LIVE GOLD!",        NULL },
			{ "Tokyo Midtown Ver.",        NULL },
			{ "VMU Ver.",                  NULL },
			{ "Game Master Ver.",          NULL },
			{ "Android Green",             NULL },
			{ "Ticketmaster Azure",        NULL },
			{ "Google Red",                NULL },
			{ "Google Blue",               NULL },
			{ "Google Yellow",             NULL },
			{ "Google Green",              NULL },
			{ "WonderSwan Ver.",           NULL },
			{ "Neo Geo Pocket Ver.",       NULL },
			{ "Dew Green",                 NULL },
			{ "Coca-Cola Red",             NULL },
			{ "GameKing Ver.",             NULL },
			{ "Do The Dew Ver.",           NULL },
			{ "Digivice Ver.",             NULL },
			{ "Bikini Bottom Ver.",        NULL },
			{ "Blossom Pink",              NULL },
			{ "Bubbles Blue",              NULL },
			{ "Buttercup Green",           NULL },
			{ "NASCAR Ver.",               NULL },
			{ "Lemon-Lime Green",          NULL },
			{ "Mega Man V Ver.",           NULL },
			{ "Tamagotchi Ver.",           NULL },
			{ "Phantom Red",               NULL },
			{ "Halloween Ver.",            NULL },
			{ "Christmas Ver.",            NULL },
			{ "Cardcaptor Pink",           NULL },
			{ "Pretty Guardian Gold",      NULL },
			{ "Camoflauge Ver.",           NULL },
			{ "Legendary Sp. Saiyan",      NULL },
			{ "Super Saiyan Rose",         NULL },
			{ "Super Saiyan",              NULL },
			{ "Mst. Ult. Instinct",        NULL },
			{ "Saint Snow Red",            NULL },
			{ "Yellow Banana",             NULL },
			{ "Green Banana",              NULL },
			{ "Super Saiyan 3",            NULL },
			{ "Sp. Saiyan Blue Evo.",      NULL },
			{ "Pocket Tales Ver.",         NULL },
			{ "Investigation Yellow",      NULL },
			{ "S.E.E.S. Blue",             NULL },
			{ "Game Awards Cyan",          NULL },
			{ "Hokage Orange",             NULL },
			{ "Straw Hat Red",             NULL },
			{ "Sword Art Cyan",            NULL },
			{ "Deku Alpha Emerald",        NULL },
			{ "Blue Stripes Ver.",         NULL },
			{ "Stone Orange",              NULL },
			{ NULL, NULL }
		}
	},
	{
		.key = "gambatte_gb_palette_twb64_2",
		.desc = "TWB64 - Pack 2",
		.default_value = "765PRO Pink",
		.options = {
			{ "765PRO Pink",               NULL },
			{ "CINDERELLA Blue",           NULL },
			{ "MILLION Yellow!",           NULL },
			{ "SideM Green",               NULL },
			{ "SHINY Sky Blue",            NULL },
			{ "Angry Volcano Ver.",        NULL },
			{ "Yo-kai Pink",               NULL },
			{ "Yo-kai Green",              NULL },
			{ "Yo-kai Blue",               NULL },
			{ "Yo-kai Purple",             NULL },
			{ "Aquatic Iro",               NULL },
			{ "Tea Midori",                NULL },
			{ "Sakura Pink",               NULL },
			{ "Wisteria Murasaki",         NULL },
			{ "Oni Aka",                   NULL },
			{ "Golden Kiiro",              NULL },
			{ "Silver Shiro",              NULL },
			{ "Fruity Orange",             NULL },
			{ "AKB48 Pink",                NULL },
			{ "Miku Blue",                 NULL },
			{ "Fairy Tail Red",            NULL },
			{ "Survey Corps Brown",        NULL },
			{ "Island Green",              NULL },
			{ "Mania Plus Green",          NULL },
			{ "Ninja Turtle Green",        NULL },
			{ "Slime Blue",                NULL },
			{ "Lime Midori",               NULL },
			{ "Ghostly Aoi",               NULL },
			{ "Retro Bogeda",              NULL },
			{ "Royal Blue",                NULL },
			{ "Neon Purple",               NULL },
			{ "Neon Orange",               NULL },
			{ "Moonlight Vision",          NULL },
			{ "Tokyo Red",                 NULL },
			{ "Paris Gold",                NULL },
			{ "Beijing Blue",              NULL },
			{ "Pac-Man Yellow",            NULL },
			{ "Irish Green",               NULL },
			{ "Kakarot Orange",            NULL },
			{ "Dragon Ball Orange",        NULL },
			{ "Christmas Gold",            NULL },
			{ "Pepsi Blue",                NULL },
			{ "Bubblun Green",             NULL },
			{ "Bobblun Blue",              NULL },
			{ "Baja Blast Storm",          NULL },
			{ "Olympic Gold",              NULL },
			{ "Value Orange",              NULL },
			{ "Liella Purple!",            NULL },
			{ "Olympic Silver",            NULL },
			{ "Olympic Bronze",            NULL },
			{ "ANA Sky Blue",              NULL },
			{ "Nijigasaki Orange",         NULL },
			{ "HoloBlue",                  NULL },
			{ "Wrestling Red",             NULL },
			{ "Yoshi Egg Green",           NULL },
			{ "Pokedex Red",               NULL },
			{ "Disney Dream Blue",         NULL },
			{ "Xbox Green",                NULL },
			{ "Sonic Mega Blue",           NULL },
			{ "G4 Orange",                 NULL },
			{ "Scarlett Green",            NULL },
			{ "Glitchy Blue",              NULL },
			{ "Classic LCD",               NULL },
			{ "3DS VC Ver.",               NULL },
			{ "PocketStation Ver.",        NULL },
			{ "Game and Gold",             NULL },
			{ "Smurfy Blue",               NULL },
			{ "Swampy Ogre Green",         NULL },
			{ "Sailor Spinach Green",      NULL },
			{ "Shenron Green",             NULL },
			{ "Berserk Blood",             NULL },
			{ "Super Star Pink",           NULL },
			{ "Gamebuino Clas. Ver.",      NULL },
			{ "Barbie Pink",               NULL },
			{ "Star Command Green",        NULL },
			{ "Nokia 3310 Ver.",           NULL },
			{ "Clover Green",              NULL },
			{ "Crash Orange",              NULL },
			{ "Famicom Disk Yellow",       NULL },
			{ "Team Rocket Red",           NULL },
			{ "SEIKO Timer Yellow",        NULL },
			{ "PINK109",                   NULL },
			{ "Doraemon Blue",             NULL },
			{ "Fury Blue",                 NULL },
			{ "Rockstar Orange",           NULL },
			{ "Puyo Puyo Green",           NULL },
			{ "Susan G. Pink",             NULL },
			{ "Pizza Hut Red",             NULL },
			{ "Plumbob Green",             NULL },
			{ "Grand Ivory",               NULL },
			{ "Demon's Gold",              NULL },
			{ "SEGA Tokyo Blue",           NULL },
			{ "Champion Blue",             NULL },
			{ "DK Barrel Brown",           NULL },
			{ "Evangelion Green",          NULL },
			{ "Equestrian Purple",         NULL },
			{ "Autobot Red",               NULL },
			{ "Niconico Sea Green",        NULL },
			{ "Duracell Copper",           NULL },
			{ "TOKYO SKYTREE BLUE",        NULL },
			{ NULL, NULL },
		}
	},
	{
		.key = "gambatte_gbc_color_correction",
		.info = "Adjusts colors to match the display of real GBC hardware. 'GBC Only' only applies correction when playing GBC games or using a GBC palette."
	},
	{
		.key = "gambatte_gbc_color_correction_mode",
		.desc = "CC Mode",
		.info = "'Accurate' produces output almost indistinguishable from a real GBC LCD panel. 'Fast' merely darkens colors and reduces saturation."
	},
	{
		.key = "gambatte_gbc_frontlight_position",
		.desc = "CC Frontlight",
		.info = "Simulates the GBC LCD panel when illuminated from different angles. This setting only applies when 'Color Correction Mode' is set to 'Accurate'."
	},
	{
		.key = "gambatte_dark_filter_level",
		.desc = "Dark Level",
		.info = "Enable luminosity-based brightness reduction. May be used to avoid glare/eye strain when playing games with white backgrounds."
	},
	{
		.key = "gambatte_gb_hwmode",
		.desc = "Hardware (restart)",
		.info = "Which type of hardware to emulate. 'Auto' is recommended. 'GBA' unlocks extra features in certain 'GBA enhanced' Game Boy Color games."
	},
	{
		.key = "gambatte_gb_bootloader",
		.desc = "Boot Logo (restart)",
	},
	{
		.key = "gambatte_mix_frames",
		.desc = "Blending",
		.info = "Simulates LCD ghosting effects. 'Simple' performs a 50:50 mix. 'Ghosting' mimics LCD response times with multiple buffered frames.",
		.options = {
			[2] = { "lcd_ghosting",         "Ghosting (Accurate)" },
			[3] = { "lcd_ghosting_fast",    "Ghosting (Fast)"     },
			[4] = { "lcd_ghosting_fastest", "Ghosting (Fastest)"  },
		}
	},
	{
		.key = "gambatte_up_down_allowed",
		.desc = "Opp. Directions",
		.info = "Enabling this will allow pressing / quickly alternating / holding both left and right (or up and down) directions at the same time."
	},
	{
		.key = "gambatte_rumble_level",
		.blocked = true
	},
	{
		.key = "gambatte_show_gb_link_settings",
		.blocked = true
	},
	{ NULL }
};

me_bind_action gambatte_ctrl_actions[] =
{
	{ "UP       ",  1 << RETRO_DEVICE_ID_JOYPAD_UP},
	{ "DOWN     ",  1 << RETRO_DEVICE_ID_JOYPAD_DOWN },
	{ "LEFT     ",  1 << RETRO_DEVICE_ID_JOYPAD_LEFT },
	{ "RIGHT    ",  1 << RETRO_DEVICE_ID_JOYPAD_RIGHT },
	{ "A BUTTON ",  1 << RETRO_DEVICE_ID_JOYPAD_A },
	{ "B BUTTON ",  1 << RETRO_DEVICE_ID_JOYPAD_B },
	{ "A TURBO  ",  1 << RETRO_DEVICE_ID_JOYPAD_X },
	{ "B TURBO  ",  1 << RETRO_DEVICE_ID_JOYPAD_Y },
	{ "START    ",  1 << RETRO_DEVICE_ID_JOYPAD_START },
	{ "SELECT   ",  1 << RETRO_DEVICE_ID_JOYPAD_SELECT },
	{ NULL,       0 }
};

#define gambatte_overrides {                                    \
	.core_name = "gambatte",                                \
	.actions = gambatte_ctrl_actions,                       \
	.action_size = array_size(gambatte_ctrl_actions),       \
	.options = gambatte_core_option_overrides               \
}
